server:
  port: 8087
spring:
  profiles:
    active: ${SPRING_PROFILES_INCLUDE:dev}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://127.0.0.1:8888}
  cloud:
    config:
      label: ${SPRING_CLOUD_CONFIG_LABEL:master}
      username: ${SPRING_CLOUD_CONFIG_USERNAME:geek_user}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD:geek_pass}

  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'smarttest.gg@gmail.com'
    password: 'smart333ggll'
    properties:
      mail:
        smtp:
          auth: 'true'
          starttls:
            enable: 'true'
